## ---- Load data ----
dat <- readxl::read_xlsx(
  paste0("dat/", respondi_xlsx_name),
  sheet = respondi_sheet_name) %>%
  dplyr::select(
    v_16,
    v_17,
    v_21,
    v_22,
    v_23,
    v_27,
    v_28,
    v_29,
    v_30,
    v_32,
    v_38,
    v_39,
    v_40,
    v_41,
    v_8111f,
    v_140,
    v_144,
    v_148,
    v_152,
    v_141,
    v_145,
    v_149,
    v_153,
    v_142,
    v_146,
    v_150,
    v_154,
    v_143,
    v_147,
    v_151,
    v_155,
    v_a04c0,
    v_06bd1,
    v_19cba,
    v_983a0,
    v_49,
    v_50,
    v_51,
    v_52,
    v_53,
    v_54,
    v_55,
    v_56,
    v_57,
    v_58,
    v_59,
    v_60,
    v_61,
    v_62,
    v_65,
    v_67,
    v_68,
    v_69,
    v_70,
    v_71,
    v_72,
    v_73,
    v_74,
    v_76,
    v_77,
    v_78,
    v_79,
    v_81,
    v_82,
    v_83,
    v_84,
    v_85,
    v_156,
    v_169,
    v_173,
    v_177,
    v_181,
    v_170,
    v_174,
    v_178,
    v_182,
    v_171,
    v_175,
    v_179,
    v_183,
    v_172,
    v_176,
    v_180,
    v_184,
    v_120,
    v_8e7ef,
    v_f7e25,
    v_068d7,
    v_93,
    v_94,
    v_95,
    v_96,
    v_97,
    v_98,
    v_99,
    v_100,
    v_101,
    v_102,
    v_103,
    v_104,
    v_185,
    v_106,
    v_107,
    v_108,
    v_114,
    v_115,
    v_121,
    v_122,
    v_123,
    v_124,
    v_125,
    v_126,
    v_127,
    v_128,
    v_130,
    v_131,
    c_0006,
    lfdn
  ) %>%
  dplyr::mutate_all(.funs = ~ dplyr::if_else(. == -77, NA_real_, .)) %>%
  dplyr::mutate_at(
    .vars = vars(v_16, v_17),
    .funs = ~ dplyr::if_else(!(. %in% 1:11), NA_real_, . - 1)
  ) %>%
  dplyr::mutate_at(
    .vars = vars(v_21, v_22, v_23),
    .funs = ~ dplyr::if_else(!(. %in% 1:12), NA_real_, . - 1)
  ) %>%
  dplyr::mutate_at(.vars = vars(v_114),
                   .funs = ~ dplyr::if_else(!(. %in% 1:6), NA_real_, .)) %>%
  dplyr::mutate_at(.vars = vars(v_115),
                   .funs = ~ dplyr::if_else(!(. %in% 1:3), NA_real_, .)) %>%
  dplyr::mutate_at(
    .vars = vars(
      v_a04c0,
      v_06bd1,
      v_19cba,
      v_983a0,
      v_120,
      v_8e7ef,
      v_f7e25,
      v_068d7
    ),
    .funs = ~ dplyr::if_else(!(. %in% 1:4), NA_real_, .)
  ) %>%
  dplyr::mutate_all( ~ as.integer(.)) %>%
  dplyr::rename(
    work_atmos = v_16,
    work_condi = v_17,
    covid_resea = v_21,
    covid_teach = v_22,
    covid_admin = v_23,
    covid_neg_psych = v_27,
    covid_neg_famil = v_28,
    covid_neg_equip = v_29,
    covid_neg_socia = v_30,
    covid_neg_other = v_32,
    self_insult = v_38,
    self_threat = v_39,
    self_molest = v_40,
    self_discri = v_41,
    self_none   = v_8111f,
    self_insult_col = v_140,
    self_insult_sup = v_144,
    self_insult_oth = v_148,
    self_insult_ref = v_152,
    self_threat_col = v_141,
    self_threat_sup = v_145,
    self_threat_oth = v_149,
    self_threat_ref = v_153,
    self_molest_col = v_142,
    self_molest_sup = v_146,
    self_molest_oth = v_150,
    self_molest_ref = v_154,
    self_discri_col = v_143,
    self_discri_sup = v_147,
    self_discri_oth = v_151,
    self_discri_ref = v_155,
    self_insult_freq = v_a04c0,
    self_threat_freq = v_06bd1,
    self_molest_freq = v_19cba,
    self_discri_freq = v_983a0,
    self_reason_gender = v_49,
    self_reason_parent = v_50,
    self_reason_1stgen = v_51,
    self_reason_handic = v_52,
    self_reason_lgbtq  = v_53,
    self_reason_ethnic = v_54,
    self_reason_relig  = v_55,
    self_reason_citiz  = v_56,
    self_reason_lang   = v_57,
    self_reason_occup  = v_58,
    self_reason_appear = v_59,
    self_reason_other  = v_60,
    self_reason_refuse = v_61,
    self_reason_none   = v_62,
    self_conseq_career = v_65,
    self_support = v_67,
    self_support_col = v_68,
    self_support_dep = v_69,
    self_support_eoo = v_70,
    self_support_sup = v_71,
    self_support_adm = v_72,
    self_support_fam = v_73,
    self_support_oth = v_74,
    self_nosup_fear = v_76,
    self_nosup_ineffective = v_77,
    self_nosup_dkwhere = v_78,
    self_nosup_other = v_79,
    self_conseq_offender = v_81,
    others_insult = v_82,
    others_threat = v_83,
    others_molest = v_84,
    others_discri = v_85,
    others_none = v_156,
    others_insult_col = v_169,
    others_insult_sup = v_173,
    others_insult_oth = v_177,
    others_insult_ref = v_181,
    others_threat_col = v_170,
    others_threat_sup = v_174,
    others_threat_oth = v_178,
    others_threat_ref = v_182,
    others_molest_col = v_171,
    others_molest_sup = v_175,
    others_molest_oth = v_179,
    others_molest_ref = v_183,
    others_discri_col = v_172,
    others_discri_sup = v_176,
    others_discri_oth = v_180,
    others_discri_ref = v_184,
    others_insult_freq = v_120,
    others_threat_freq = v_8e7ef,
    others_molest_freq = v_f7e25,
    others_discri_freq = v_068d7,
    others_reason_gender = v_93,
    others_reason_parent = v_94,
    others_reason_1stgen = v_95,
    others_reason_handic = v_96,
    others_reason_lgbtq  = v_97,
    others_reason_ethnic = v_98,
    others_reason_relig  = v_99,
    others_reason_citiz  = v_100,
    others_reason_lang   = v_101,
    others_reason_occup  = v_102,
    others_reason_appear = v_103,
    others_reason_other  = v_104,
    others_reason_refuse = v_185,
    others_reason_none   = v_106,
    others_conseq_career = v_107,
    others_conseq_offender = v_108,
    personal_occup = v_114,
    personal_gender = v_115,
    personal_parent = v_121,
    personal_1stgen = v_122,
    personal_lgbtq = v_123,
    personal_handic  = v_124,
    personal_ethnic = v_125,
    personal_relig  = v_126,
    personal_citiz  = v_127,
    personal_lang   = v_128,
    personal_refuse = v_130,
    personal_none   = v_131,
    complete = c_0006
  ) %>%
  dplyr::filter(complete == 1)

## Enforce filters
dat <- dat %>%
  dplyr::rowwise() %>%
  dplyr::mutate_at(
    .vars = vars(dplyr::starts_with("covid_neg_")),
    .funs = ~ dplyr::if_else(!any(
      c(covid_resea,
        covid_teach,
        covid_admin) %in% 1:5
    ),
    NA_integer_,
    .)
  ) %>%
  dplyr::ungroup() %>%
  dplyr::mutate_at(
    .vars = vars(
      dplyr::starts_with("self_insult_"),
      dplyr::starts_with("self_threat_"),
      dplyr::starts_with("self_molest_"),
      dplyr::starts_with("self_discri_"),
      dplyr::starts_with("self_conseq"),
      dplyr::starts_with("self_reason"),
      dplyr::starts_with("self_support"),
      dplyr::starts_with("self_nosup")
      ),
    .funs = ~ dplyr::if_else(is.na(self_none) | self_none == 1,
                             NA_integer_,
                             .)
  ) %>%
  dplyr::mutate_at(
    .vars = vars(
      dplyr::starts_with("others_insult_"),
      dplyr::starts_with("others_threat_"),
      dplyr::starts_with("others_molest_"),
      dplyr::starts_with("others_discri_"),
      dplyr::starts_with("others_conseq"),
      dplyr::starts_with("others_reason")
    ),
    .funs = ~ dplyr::if_else(is.na(others_none) | others_none == 1,
                             NA_integer_,
                             .)
  ) %>%
  dplyr::mutate_at(
    .vars = vars(dplyr::starts_with("self_support_")),
    .funs = ~ dplyr::if_else(self_support == 2,
                             ., 
                             NA_integer_)
  )  %>%
  dplyr::mutate_at(
    .vars = vars(dplyr::starts_with("self_nosup_")),
    .funs = ~ dplyr::if_else(self_support == 1,
                             ., 
                             NA_integer_)
  ) %>%
  dplyr::mutate_at(
    .vars = vars(dplyr::starts_with("personal_") &
                   !dplyr::contains("occup") &
                   !dplyr::contains("gender") &
                   !dplyr::contains("refuse")),
    .funs = ~ dplyr::if_else(personal_refuse == 1,
                             NA_integer_,
                             .)
  )

## ---- Save ----
saveRDS(dat, file = "dat/quant_vars.rds")
